CREATE TABLE `b_awz_bx24lead_providers` (
    ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ENTITY_ID varchar(65) NOT NULL,
    HOOK varchar(255) NOT NULL,
    'NAME' varchar(255) NOT NULL,
    ACTIVE varchar(1),
    PRM text,
    PRIMARY KEY (ID)
);
CREATE INDEX b_awz_bx24lead_providers_ix_entity_id_active ON b_awz_bx24lead_providers (ENTITY_ID, ACTIVE);