CREATE TABLE IF NOT EXISTS `b_awz_bx24lead_providers` (
`ID` int(18) NOT NULL AUTO_INCREMENT,
`ENTITY_ID` varchar(65) NOT NULL,
`HOOK` varchar(255) NOT NULL,
`NAME` varchar(255) NOT NULL,
`ACTIVE` varchar(1) DEFAULT "N",
`PRM` varchar(6255) DEFAULT NULL,
PRIMARY KEY (`ID`),
index ENTITY_ID_ACTIVE (ENTITY_ID, ACTIVE)
) AUTO_INCREMENT=1;